name: pdiff
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgomp=13.2.0=h807b86a_2
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.43.0=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.3=hd590300_0
  - pip=23.2.1=pyhd8ed1ab_0
  - python=3.8.17=he550d4f_0_cpython
  - python_abi=3.8=4_cp38
  - readline=8.2=h8228510_1
  - ruamel_yaml=0.15.80=py38h01eb140_1009
  - setuptools=68.2.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - albumentations==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.1.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.13.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - braceexpand==0.1.7
      - cachetools==5.3.2
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.2.0
      - click==8.1.7
      - cmake==3.27.5
      - comm==0.2.0
      - contourpy==1.1.1
      - cycler==0.11.0
      - dataclasses==0.6
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - exifread-nocycle==3.0.1
      - fairscale==0.4.4
      - fastjsonschema==2.19.0
      - filelock==3.12.4
      - fire==0.4.0
      - fonttools==4.42.1
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2022.11.0
      - gitdb==4.0.10
      - gitpython==3.1.37
      - google-auth==2.24.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.59.3
      - huggingface-hub==0.17.2
      - hydra==2.5
      - hydra-core==1.3.2
      - idna==3.4
      - imageio==2.31.3
      - img2dataset==1.42.0
      - importlib-metadata==6.9.0
      - importlib-resources==6.1.0
      - ipykernel==6.27.1
      - ipython==8.12.3
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-core==5.5.0
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.1
      - jupyter-server==2.12.1
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.2
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lightning==2.1.2
      - lightning-utilities==0.10.0
      - lit==16.0.6
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.7.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - nbclient==0.9.0
      - nbconvert==7.12.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.1
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python-headless==4.8.0.76
      - overrides==7.4.0
      - packaging==23.1
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.1.0
      - prometheus-client==0.19.0
      - promise==2.3
      - prompt-toolkit==3.0.41
      - protobuf==3.20.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==10.0.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - pycparser==2.21
      - pygments==2.17.2
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytorch-lightning==2.1.2
      - pytz==2023.3.post1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - qudida==0.0.4
      - referencing==0.32.0
      - regex==2023.8.8
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.13.2
      - rsa==4.9
      - ruamel-yaml==0.17.32
      - ruamel-yaml-clib==0.2.7
      - sacremoses==0.0.53
      - scikit-image==0.21.0
      - scikit-learn==1.3.1
      - scipy==1.10.1
      - send2trash==1.8.2
      - sentry-sdk==1.31.0
      - setproctitle==1.3.2
      - shortuuid==1.0.11
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - sympy==1.12
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.3.0
      - terminado==0.18.0
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - timm==0.4.12
      - tinycss2==1.2.1
      - tokenizers==0.10.3
      - tomli==2.0.1
      - torch==2.0.1
      - torchmetrics==1.2.1
      - torchvision==0.15.2
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.0
      - transformers==4.15.0
      - triton==2.0.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - uri-template==1.3.0
      - urllib3==2.0.5
      - wandb==0.12.21
      - wcwidth==0.2.12
      - webcolors==1.13
      - webdataset==0.2.57
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - yarl==1.9.3
      - zipp==3.17.0
