name: vae

model:
  arch:
    _target_: core.module.modules.odvae.medium
    in_dim: 2048
    latent_dim: 12
    kld_weight: 0.005

  data_transform:

train:
  optimizer:
    _target_: torch.optim.AdamW
    lr: 1e-3
    weight_decay: 2e-6

  lr_scheduler:

  loss_func:
    _target_: torch.nn.MSELoss
    reduction: sum

  trainer:
    _target_:  pytorch_lightning.trainer.Trainer
    strategy: 'auto'
    max_epochs: 30000
    check_val_every_n_epoch:
    val_check_interval : 3000
    log_every_n_steps: 1
    limit_val_batches: 1
    limit_test_batches: 1
    devices:
    - ${device.id}

    enable_model_summary: false

    callbacks:
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: ${output_dir}/${system.name}/${now:%Y-%m-%d-%H-%M-%S}/checkpoints
      filename: "{epoch}-{loss:.4f}"
      monitor: 'loss'
      mode: 'min'
      save_top_k: 2
      save_last: true
      verbose: true

    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: ${output_dir}/${system.name}/${now:%Y-%m-%d-%H-%M-%S}/checkpoints
      filename: "{epoch}-{ae_acc:.4f}"
      monitor: 'vae_acc'
      mode: 'max'
      save_top_k: 2
      save_last: false
      verbose: true

    logger:
      _target_:  pytorch_lightning.loggers.TensorBoardLogger
      save_dir: ${output_dir}/${system.name}/${now:%Y-%m-%d-%H-%M-%S}/tensorboard
      name: '.'
      version: '.'
